{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "roastbook.postgresqlName" . }}
  labels:
    {{- include "roastbook.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "roastbook.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
