{{- if and .Values.hodor.enabled (not .Values.hodor.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roastbook.fullname" . }}-hodor
  labels:
    {{- include "roastbook.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "hodor.password is required when hodor is enabled" .Values.hodor.password | quote }}
  secret: {{ .Values.hodor.secret | default (randAlphaNum 64) | quote }}
{{- end }}
---
{{- if and (not .Values.postgresql.existingSecret) (not .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roastbook.fullname" . }}-db
  labels:
    {{- include "roastbook.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.external.url }}
  url: {{ .Values.postgresql.external.url | quote }}
  {{- else }}
  url: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.postgresql.auth.username (required "postgresql.auth.password is required" .Values.postgresql.auth.password) (required "postgresql.external.host is required" .Values.postgresql.external.host) .Values.postgresql.external.port .Values.postgresql.auth.database | quote }}
  {{- end }}
{{- end }}
