// The hint preserves the descriptor's position in the flavor-wheel hierarchy
// for future AI-assisted tagging. The UI intentionally presents one ungrouped
// list: hierarchy is metadata, not a browsing taxonomy.
export const TASTE_TAGS = [
  {
    name: 'Fruity',
    category: 'Flavor',
    hint: 'Flavor wheel: Fruity. A general ripe-fruit aroma when no more specific fruit family fits.',
    extractionAxis: '0.3',
    strengthAxis: '0.5',
  },
  {
    name: 'Berry',
    category: 'Flavor',
    hint: 'Flavor wheel: Fruity → Berry. Strawberry, raspberry, blueberry, or blackberry-like aromas.',
    extractionAxis: '0.3',
    strengthAxis: '0.5',
  },
  {
    name: 'Dried fruit',
    category: 'Flavor',
    hint: 'Flavor wheel: Fruity → Dried fruit. Raisin, prune, date, or dried-berry aromas.',
    extractionAxis: '0.4',
    strengthAxis: '0.6',
  },
  {
    name: 'Citrus',
    category: 'Flavor',
    hint: 'Flavor wheel: Fruity → Citrus fruit. Lemon, lime, orange, grapefruit, or citrus-peel aromas.',
    extractionAxis: '0.4',
    strengthAxis: '0.4',
  },
  {
    name: 'Stone fruit',
    category: 'Flavor',
    hint: 'Flavor wheel: Fruity → Other fruit. Peach, apricot, plum, nectarine, or cherry-like aromas.',
    extractionAxis: '0.35',
    strengthAxis: '0.5',
  },
  {
    name: 'Tropical fruit',
    category: 'Flavor',
    hint: 'Flavor wheel: Fruity → Other fruit. Pineapple, mango, papaya, passion fruit, or coconut-like aromas.',
    extractionAxis: '0.35',
    strengthAxis: '0.55',
  },
  {
    name: 'Floral',
    category: 'Flavor',
    hint: 'Flavor wheel: Floral. Jasmine, rose, chamomile, or tea-like aromas.',
    extractionAxis: '0.2',
    strengthAxis: '0.3',
  },
  {
    name: 'Chocolate',
    category: 'Flavor',
    hint: 'Flavor wheel: Nutty/Cocoa → Cocoa. Milk chocolate, dark chocolate, or cocoa-like aromas.',
    extractionAxis: '0.6',
    strengthAxis: '0.7',
  },
  {
    name: 'Nutty',
    category: 'Flavor',
    hint: 'Flavor wheel: Nutty/Cocoa → Nutty. Almond, hazelnut, peanut, or walnut-like aromas.',
    extractionAxis: '0.5',
    strengthAxis: '0.6',
  },
  {
    name: 'Caramel',
    category: 'Flavor',
    hint: 'Flavor wheel: Sweet → Brown sugar. Caramelized, honey, molasses, or maple-like aromas.',
    extractionAxis: '0.6',
    strengthAxis: '0.6',
  },
  {
    name: 'Vanilla',
    category: 'Flavor',
    hint: 'Flavor wheel: Sweet → Vanilla. Vanilla, marshmallow, or custard-like sweet aromatics.',
    extractionAxis: '0.5',
    strengthAxis: '0.5',
  },
  {
    name: 'Spicy',
    category: 'Flavor',
    hint: 'Flavor wheel: Spices. Cinnamon, clove, nutmeg, anise, or pepper-like aromas.',
    extractionAxis: '0.7',
    strengthAxis: '0.6',
  },
  {
    name: 'Roasted',
    category: 'Flavor',
    hint: 'Flavor wheel: Roasted. Toasted, coffee-like, smoky, or tobacco-like aromas.',
    extractionAxis: '0.75',
    strengthAxis: '0.75',
  },
  {
    name: 'Cereal',
    category: 'Flavor',
    hint: 'Flavor wheel: Roasted → Cereal. Grain, malt, or fresh-bread aromas.',
    extractionAxis: '0.55',
    strengthAxis: '0.45',
  },
  {
    name: 'Green / vegetative',
    category: 'Flavor',
    hint: 'Flavor wheel: Green/Vegetative. Fresh, herbal, peapod, hay, or unripe-plant aromas.',
    extractionAxis: '0.25',
    strengthAxis: '0.4',
  },
  {
    name: 'Earthy',
    category: 'Flavor',
    hint: 'Flavor wheel: Other → Musty/Earthy. Soil, damp wood, or dusty aromas.',
    extractionAxis: '0.7',
    strengthAxis: '0.7',
  },
  {
    name: 'Fermented',
    category: 'Flavor',
    hint: 'Flavor wheel: Sour/Fermented → Fermented. Winey, overripe, or alcohol-like aromas, separate from acidity intensity.',
    extractionAxis: '0.45',
    strengthAxis: '0.7',
  },
  {
    name: 'Woody',
    category: 'Flavor',
    hint: 'Flavor wheel: Other → Papery/Musty → Woody. Dry wood, bark, cedar, or pencil-shaving aromas.',
    extractionAxis: '0.7',
    strengthAxis: '0.55',
  },
] as const
