export const TASTE_TAGS = [
  { name: "Fruity", category: "Flavor", extractionAxis: "0.3", strengthAxis: "0.5" },
  { name: "Citrus", category: "Flavor", extractionAxis: "0.4", strengthAxis: "0.4" },
  { name: "Berry", category: "Flavor", extractionAxis: "0.3", strengthAxis: "0.5" },
  { name: "Chocolate", category: "Flavor", extractionAxis: "0.6", strengthAxis: "0.7" },
  { name: "Nutty", category: "Flavor", extractionAxis: "0.5", strengthAxis: "0.6" },
  { name: "Caramel", category: "Flavor", extractionAxis: "0.6", strengthAxis: "0.6" },
  { name: "Floral", category: "Flavor", extractionAxis: "0.2", strengthAxis: "0.3" },
  { name: "Honey", category: "Flavor", extractionAxis: "0.5", strengthAxis: "0.5" },
  { name: "Spicy", category: "Flavor", extractionAxis: "0.7", strengthAxis: "0.6" },
  { name: "Earthy", category: "Flavor", extractionAxis: "0.7", strengthAxis: "0.7" },
  { name: "Bright", category: "Acidity", extractionAxis: "0.2", strengthAxis: "0.3" },
  { name: "Crisp", category: "Acidity", extractionAxis: "0.3", strengthAxis: "0.4" },
  { name: "Mellow", category: "Acidity", extractionAxis: "0.6", strengthAxis: "0.5" },
  { name: "Sour", category: "Defect", extractionAxis: "0.1", strengthAxis: "0.3" },
  { name: "Bitter", category: "Defect", extractionAxis: "0.9", strengthAxis: "0.8" },
  { name: "Astringent", category: "Defect", extractionAxis: "0.8", strengthAxis: "0.7" },
  { name: "Syrupy", category: "Body", extractionAxis: "0.6", strengthAxis: "0.8" },
  { name: "Creamy", category: "Body", extractionAxis: "0.5", strengthAxis: "0.7" },
  { name: "Thin", category: "Body", extractionAxis: "0.3", strengthAxis: "0.2" },
  { name: "Full", category: "Body", extractionAxis: "0.6", strengthAxis: "0.8" },
] as const
