/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisitsIndexRouteImport } from './routes/visits/index'
import { Route as ShotsIndexRouteImport } from './routes/shots/index'
import { Route as ShopsIndexRouteImport } from './routes/shops/index'
import { Route as RoastersIndexRouteImport } from './routes/roasters/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as PlacesIndexRouteImport } from './routes/places/index'
import { Route as GearIndexRouteImport } from './routes/gear/index'
import { Route as BrewingMethodsIndexRouteImport } from './routes/brewing-methods/index'
import { Route as BeansIndexRouteImport } from './routes/beans/index'
import { Route as VisitsNewRouteImport } from './routes/visits/new'
import { Route as VisitsVisitIdRouteImport } from './routes/visits/$visitId'
import { Route as ShotsNewRouteImport } from './routes/shots/new'
import { Route as ShotsShotIdRouteImport } from './routes/shots/$shotId'
import { Route as ShopsNewRouteImport } from './routes/shops/new'
import { Route as ShopsCoffeeShopIdRouteImport } from './routes/shops/$coffeeShopId'
import { Route as RoastersNewRouteImport } from './routes/roasters/new'
import { Route as RoastersRoasterIdRouteImport } from './routes/roasters/$roasterId'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes/$recipeId'
import { Route as GearNewRouteImport } from './routes/gear/new'
import { Route as GearGearIdRouteImport } from './routes/gear/$gearId'
import { Route as BeansNewRouteImport } from './routes/beans/new'
import { Route as BeansBeanIdRouteImport } from './routes/beans/$beanId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsIndexRoute = VisitsIndexRouteImport.update({
  id: '/visits/',
  path: '/visits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShotsIndexRoute = ShotsIndexRouteImport.update({
  id: '/shots/',
  path: '/shots/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastersIndexRoute = RoastersIndexRouteImport.update({
  id: '/roasters/',
  path: '/roasters/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const GearIndexRoute = GearIndexRouteImport.update({
  id: '/gear/',
  path: '/gear/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrewingMethodsIndexRoute = BrewingMethodsIndexRouteImport.update({
  id: '/brewing-methods/',
  path: '/brewing-methods/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansIndexRoute = BeansIndexRouteImport.update({
  id: '/beans/',
  path: '/beans/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsNewRoute = VisitsNewRouteImport.update({
  id: '/visits/new',
  path: '/visits/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsVisitIdRoute = VisitsVisitIdRouteImport.update({
  id: '/visits/$visitId',
  path: '/visits/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShotsNewRoute = ShotsNewRouteImport.update({
  id: '/shots/new',
  path: '/shots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShotsShotIdRoute = ShotsShotIdRouteImport.update({
  id: '/shots/$shotId',
  path: '/shots/$shotId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsNewRoute = ShopsNewRouteImport.update({
  id: '/shops/new',
  path: '/shops/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsCoffeeShopIdRoute = ShopsCoffeeShopIdRouteImport.update({
  id: '/shops/$coffeeShopId',
  path: '/shops/$coffeeShopId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastersNewRoute = RoastersNewRouteImport.update({
  id: '/roasters/new',
  path: '/roasters/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastersRoasterIdRoute = RoastersRoasterIdRouteImport.update({
  id: '/roasters/$roasterId',
  path: '/roasters/$roasterId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const GearNewRoute = GearNewRouteImport.update({
  id: '/gear/new',
  path: '/gear/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GearGearIdRoute = GearGearIdRouteImport.update({
  id: '/gear/$gearId',
  path: '/gear/$gearId',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansNewRoute = BeansNewRouteImport.update({
  id: '/beans/new',
  path: '/beans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansBeanIdRoute = BeansBeanIdRouteImport.update({
  id: '/beans/$beanId',
  path: '/beans/$beanId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/beans/$beanId': typeof BeansBeanIdRoute
  '/beans/new': typeof BeansNewRoute
  '/gear/$gearId': typeof GearGearIdRoute
  '/gear/new': typeof GearNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/roasters/$roasterId': typeof RoastersRoasterIdRoute
  '/roasters/new': typeof RoastersNewRoute
  '/shops/$coffeeShopId': typeof ShopsCoffeeShopIdRoute
  '/shops/new': typeof ShopsNewRoute
  '/shots/$shotId': typeof ShotsShotIdRoute
  '/shots/new': typeof ShotsNewRoute
  '/visits/$visitId': typeof VisitsVisitIdRoute
  '/visits/new': typeof VisitsNewRoute
  '/beans/': typeof BeansIndexRoute
  '/brewing-methods/': typeof BrewingMethodsIndexRoute
  '/gear/': typeof GearIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/roasters/': typeof RoastersIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/shots/': typeof ShotsIndexRoute
  '/visits/': typeof VisitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/beans/$beanId': typeof BeansBeanIdRoute
  '/beans/new': typeof BeansNewRoute
  '/gear/$gearId': typeof GearGearIdRoute
  '/gear/new': typeof GearNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/roasters/$roasterId': typeof RoastersRoasterIdRoute
  '/roasters/new': typeof RoastersNewRoute
  '/shops/$coffeeShopId': typeof ShopsCoffeeShopIdRoute
  '/shops/new': typeof ShopsNewRoute
  '/shots/$shotId': typeof ShotsShotIdRoute
  '/shots/new': typeof ShotsNewRoute
  '/visits/$visitId': typeof VisitsVisitIdRoute
  '/visits/new': typeof VisitsNewRoute
  '/beans': typeof BeansIndexRoute
  '/brewing-methods': typeof BrewingMethodsIndexRoute
  '/gear': typeof GearIndexRoute
  '/places': typeof PlacesIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/roasters': typeof RoastersIndexRoute
  '/shops': typeof ShopsIndexRoute
  '/shots': typeof ShotsIndexRoute
  '/visits': typeof VisitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/beans/$beanId': typeof BeansBeanIdRoute
  '/beans/new': typeof BeansNewRoute
  '/gear/$gearId': typeof GearGearIdRoute
  '/gear/new': typeof GearNewRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/roasters/$roasterId': typeof RoastersRoasterIdRoute
  '/roasters/new': typeof RoastersNewRoute
  '/shops/$coffeeShopId': typeof ShopsCoffeeShopIdRoute
  '/shops/new': typeof ShopsNewRoute
  '/shots/$shotId': typeof ShotsShotIdRoute
  '/shots/new': typeof ShotsNewRoute
  '/visits/$visitId': typeof VisitsVisitIdRoute
  '/visits/new': typeof VisitsNewRoute
  '/beans/': typeof BeansIndexRoute
  '/brewing-methods/': typeof BrewingMethodsIndexRoute
  '/gear/': typeof GearIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/roasters/': typeof RoastersIndexRoute
  '/shops/': typeof ShopsIndexRoute
  '/shots/': typeof ShotsIndexRoute
  '/visits/': typeof VisitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/stats'
    | '/beans/$beanId'
    | '/beans/new'
    | '/gear/$gearId'
    | '/gear/new'
    | '/recipes/$recipeId'
    | '/roasters/$roasterId'
    | '/roasters/new'
    | '/shops/$coffeeShopId'
    | '/shops/new'
    | '/shots/$shotId'
    | '/shots/new'
    | '/visits/$visitId'
    | '/visits/new'
    | '/beans/'
    | '/brewing-methods/'
    | '/gear/'
    | '/places/'
    | '/recipes/'
    | '/roasters/'
    | '/shops/'
    | '/shots/'
    | '/visits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/stats'
    | '/beans/$beanId'
    | '/beans/new'
    | '/gear/$gearId'
    | '/gear/new'
    | '/recipes/$recipeId'
    | '/roasters/$roasterId'
    | '/roasters/new'
    | '/shops/$coffeeShopId'
    | '/shops/new'
    | '/shots/$shotId'
    | '/shots/new'
    | '/visits/$visitId'
    | '/visits/new'
    | '/beans'
    | '/brewing-methods'
    | '/gear'
    | '/places'
    | '/recipes'
    | '/roasters'
    | '/shops'
    | '/shots'
    | '/visits'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/stats'
    | '/beans/$beanId'
    | '/beans/new'
    | '/gear/$gearId'
    | '/gear/new'
    | '/recipes/$recipeId'
    | '/roasters/$roasterId'
    | '/roasters/new'
    | '/shops/$coffeeShopId'
    | '/shops/new'
    | '/shots/$shotId'
    | '/shots/new'
    | '/visits/$visitId'
    | '/visits/new'
    | '/beans/'
    | '/brewing-methods/'
    | '/gear/'
    | '/places/'
    | '/recipes/'
    | '/roasters/'
    | '/shops/'
    | '/shots/'
    | '/visits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  BeansBeanIdRoute: typeof BeansBeanIdRoute
  BeansNewRoute: typeof BeansNewRoute
  GearGearIdRoute: typeof GearGearIdRoute
  GearNewRoute: typeof GearNewRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  RoastersRoasterIdRoute: typeof RoastersRoasterIdRoute
  RoastersNewRoute: typeof RoastersNewRoute
  ShopsCoffeeShopIdRoute: typeof ShopsCoffeeShopIdRoute
  ShopsNewRoute: typeof ShopsNewRoute
  ShotsShotIdRoute: typeof ShotsShotIdRoute
  ShotsNewRoute: typeof ShotsNewRoute
  VisitsVisitIdRoute: typeof VisitsVisitIdRoute
  VisitsNewRoute: typeof VisitsNewRoute
  BeansIndexRoute: typeof BeansIndexRoute
  BrewingMethodsIndexRoute: typeof BrewingMethodsIndexRoute
  GearIndexRoute: typeof GearIndexRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  RoastersIndexRoute: typeof RoastersIndexRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
  ShotsIndexRoute: typeof ShotsIndexRoute
  VisitsIndexRoute: typeof VisitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/': {
      id: '/visits/'
      path: '/visits'
      fullPath: '/visits/'
      preLoaderRoute: typeof VisitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shots/': {
      id: '/shots/'
      path: '/shots'
      fullPath: '/shots/'
      preLoaderRoute: typeof ShotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roasters/': {
      id: '/roasters/'
      path: '/roasters'
      fullPath: '/roasters/'
      preLoaderRoute: typeof RoastersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear/': {
      id: '/gear/'
      path: '/gear'
      fullPath: '/gear/'
      preLoaderRoute: typeof GearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brewing-methods/': {
      id: '/brewing-methods/'
      path: '/brewing-methods'
      fullPath: '/brewing-methods/'
      preLoaderRoute: typeof BrewingMethodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/': {
      id: '/beans/'
      path: '/beans'
      fullPath: '/beans/'
      preLoaderRoute: typeof BeansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/new': {
      id: '/visits/new'
      path: '/visits/new'
      fullPath: '/visits/new'
      preLoaderRoute: typeof VisitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/$visitId': {
      id: '/visits/$visitId'
      path: '/visits/$visitId'
      fullPath: '/visits/$visitId'
      preLoaderRoute: typeof VisitsVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shots/new': {
      id: '/shots/new'
      path: '/shots/new'
      fullPath: '/shots/new'
      preLoaderRoute: typeof ShotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shots/$shotId': {
      id: '/shots/$shotId'
      path: '/shots/$shotId'
      fullPath: '/shots/$shotId'
      preLoaderRoute: typeof ShotsShotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/new': {
      id: '/shops/new'
      path: '/shops/new'
      fullPath: '/shops/new'
      preLoaderRoute: typeof ShopsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$coffeeShopId': {
      id: '/shops/$coffeeShopId'
      path: '/shops/$coffeeShopId'
      fullPath: '/shops/$coffeeShopId'
      preLoaderRoute: typeof ShopsCoffeeShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roasters/new': {
      id: '/roasters/new'
      path: '/roasters/new'
      fullPath: '/roasters/new'
      preLoaderRoute: typeof RoastersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roasters/$roasterId': {
      id: '/roasters/$roasterId'
      path: '/roasters/$roasterId'
      fullPath: '/roasters/$roasterId'
      preLoaderRoute: typeof RoastersRoasterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear/new': {
      id: '/gear/new'
      path: '/gear/new'
      fullPath: '/gear/new'
      preLoaderRoute: typeof GearNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear/$gearId': {
      id: '/gear/$gearId'
      path: '/gear/$gearId'
      fullPath: '/gear/$gearId'
      preLoaderRoute: typeof GearGearIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/new': {
      id: '/beans/new'
      path: '/beans/new'
      fullPath: '/beans/new'
      preLoaderRoute: typeof BeansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/$beanId': {
      id: '/beans/$beanId'
      path: '/beans/$beanId'
      fullPath: '/beans/$beanId'
      preLoaderRoute: typeof BeansBeanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  BeansBeanIdRoute: BeansBeanIdRoute,
  BeansNewRoute: BeansNewRoute,
  GearGearIdRoute: GearGearIdRoute,
  GearNewRoute: GearNewRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  RoastersRoasterIdRoute: RoastersRoasterIdRoute,
  RoastersNewRoute: RoastersNewRoute,
  ShopsCoffeeShopIdRoute: ShopsCoffeeShopIdRoute,
  ShopsNewRoute: ShopsNewRoute,
  ShotsShotIdRoute: ShotsShotIdRoute,
  ShotsNewRoute: ShotsNewRoute,
  VisitsVisitIdRoute: VisitsVisitIdRoute,
  VisitsNewRoute: VisitsNewRoute,
  BeansIndexRoute: BeansIndexRoute,
  BrewingMethodsIndexRoute: BrewingMethodsIndexRoute,
  GearIndexRoute: GearIndexRoute,
  PlacesIndexRoute: PlacesIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  RoastersIndexRoute: RoastersIndexRoute,
  ShopsIndexRoute: ShopsIndexRoute,
  ShotsIndexRoute: ShotsIndexRoute,
  VisitsIndexRoute: VisitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
