/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisitsIndexRouteImport } from './routes/visits/index'
import { Route as ShotsIndexRouteImport } from './routes/shots/index'
import { Route as RoastersIndexRouteImport } from './routes/roasters/index'
import { Route as PlacesIndexRouteImport } from './routes/places/index'
import { Route as GearIndexRouteImport } from './routes/gear/index'
import { Route as BeansIndexRouteImport } from './routes/beans/index'
import { Route as VisitsNewRouteImport } from './routes/visits/new'
import { Route as VisitsVisitIdRouteImport } from './routes/visits/$visitId'
import { Route as ShotsNewRouteImport } from './routes/shots/new'
import { Route as ShotsShotIdRouteImport } from './routes/shots/$shotId'
import { Route as RoastersNewRouteImport } from './routes/roasters/new'
import { Route as RoastersRoasterIdRouteImport } from './routes/roasters/$roasterId'
import { Route as PlacesNewRouteImport } from './routes/places/new'
import { Route as PlacesPlaceIdRouteImport } from './routes/places/$placeId'
import { Route as GearNewRouteImport } from './routes/gear/new'
import { Route as GearGearIdRouteImport } from './routes/gear/$gearId'
import { Route as BeansNewRouteImport } from './routes/beans/new'
import { Route as BeansBeanIdRouteImport } from './routes/beans/$beanId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsIndexRoute = VisitsIndexRouteImport.update({
  id: '/visits/',
  path: '/visits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShotsIndexRoute = ShotsIndexRouteImport.update({
  id: '/shots/',
  path: '/shots/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastersIndexRoute = RoastersIndexRouteImport.update({
  id: '/roasters/',
  path: '/roasters/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const GearIndexRoute = GearIndexRouteImport.update({
  id: '/gear/',
  path: '/gear/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansIndexRoute = BeansIndexRouteImport.update({
  id: '/beans/',
  path: '/beans/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsNewRoute = VisitsNewRouteImport.update({
  id: '/visits/new',
  path: '/visits/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsVisitIdRoute = VisitsVisitIdRouteImport.update({
  id: '/visits/$visitId',
  path: '/visits/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShotsNewRoute = ShotsNewRouteImport.update({
  id: '/shots/new',
  path: '/shots/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShotsShotIdRoute = ShotsShotIdRouteImport.update({
  id: '/shots/$shotId',
  path: '/shots/$shotId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastersNewRoute = RoastersNewRouteImport.update({
  id: '/roasters/new',
  path: '/roasters/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastersRoasterIdRoute = RoastersRoasterIdRouteImport.update({
  id: '/roasters/$roasterId',
  path: '/roasters/$roasterId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesNewRoute = PlacesNewRouteImport.update({
  id: '/places/new',
  path: '/places/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesPlaceIdRoute = PlacesPlaceIdRouteImport.update({
  id: '/places/$placeId',
  path: '/places/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)
const GearNewRoute = GearNewRouteImport.update({
  id: '/gear/new',
  path: '/gear/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GearGearIdRoute = GearGearIdRouteImport.update({
  id: '/gear/$gearId',
  path: '/gear/$gearId',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansNewRoute = BeansNewRouteImport.update({
  id: '/beans/new',
  path: '/beans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BeansBeanIdRoute = BeansBeanIdRouteImport.update({
  id: '/beans/$beanId',
  path: '/beans/$beanId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/beans/$beanId': typeof BeansBeanIdRoute
  '/beans/new': typeof BeansNewRoute
  '/gear/$gearId': typeof GearGearIdRoute
  '/gear/new': typeof GearNewRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/places/new': typeof PlacesNewRoute
  '/roasters/$roasterId': typeof RoastersRoasterIdRoute
  '/roasters/new': typeof RoastersNewRoute
  '/shots/$shotId': typeof ShotsShotIdRoute
  '/shots/new': typeof ShotsNewRoute
  '/visits/$visitId': typeof VisitsVisitIdRoute
  '/visits/new': typeof VisitsNewRoute
  '/beans/': typeof BeansIndexRoute
  '/gear/': typeof GearIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/roasters/': typeof RoastersIndexRoute
  '/shots/': typeof ShotsIndexRoute
  '/visits/': typeof VisitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/beans/$beanId': typeof BeansBeanIdRoute
  '/beans/new': typeof BeansNewRoute
  '/gear/$gearId': typeof GearGearIdRoute
  '/gear/new': typeof GearNewRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/places/new': typeof PlacesNewRoute
  '/roasters/$roasterId': typeof RoastersRoasterIdRoute
  '/roasters/new': typeof RoastersNewRoute
  '/shots/$shotId': typeof ShotsShotIdRoute
  '/shots/new': typeof ShotsNewRoute
  '/visits/$visitId': typeof VisitsVisitIdRoute
  '/visits/new': typeof VisitsNewRoute
  '/beans': typeof BeansIndexRoute
  '/gear': typeof GearIndexRoute
  '/places': typeof PlacesIndexRoute
  '/roasters': typeof RoastersIndexRoute
  '/shots': typeof ShotsIndexRoute
  '/visits': typeof VisitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/beans/$beanId': typeof BeansBeanIdRoute
  '/beans/new': typeof BeansNewRoute
  '/gear/$gearId': typeof GearGearIdRoute
  '/gear/new': typeof GearNewRoute
  '/places/$placeId': typeof PlacesPlaceIdRoute
  '/places/new': typeof PlacesNewRoute
  '/roasters/$roasterId': typeof RoastersRoasterIdRoute
  '/roasters/new': typeof RoastersNewRoute
  '/shots/$shotId': typeof ShotsShotIdRoute
  '/shots/new': typeof ShotsNewRoute
  '/visits/$visitId': typeof VisitsVisitIdRoute
  '/visits/new': typeof VisitsNewRoute
  '/beans/': typeof BeansIndexRoute
  '/gear/': typeof GearIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/roasters/': typeof RoastersIndexRoute
  '/shots/': typeof ShotsIndexRoute
  '/visits/': typeof VisitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stats'
    | '/beans/$beanId'
    | '/beans/new'
    | '/gear/$gearId'
    | '/gear/new'
    | '/places/$placeId'
    | '/places/new'
    | '/roasters/$roasterId'
    | '/roasters/new'
    | '/shots/$shotId'
    | '/shots/new'
    | '/visits/$visitId'
    | '/visits/new'
    | '/beans/'
    | '/gear/'
    | '/places/'
    | '/roasters/'
    | '/shots/'
    | '/visits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stats'
    | '/beans/$beanId'
    | '/beans/new'
    | '/gear/$gearId'
    | '/gear/new'
    | '/places/$placeId'
    | '/places/new'
    | '/roasters/$roasterId'
    | '/roasters/new'
    | '/shots/$shotId'
    | '/shots/new'
    | '/visits/$visitId'
    | '/visits/new'
    | '/beans'
    | '/gear'
    | '/places'
    | '/roasters'
    | '/shots'
    | '/visits'
  id:
    | '__root__'
    | '/'
    | '/stats'
    | '/beans/$beanId'
    | '/beans/new'
    | '/gear/$gearId'
    | '/gear/new'
    | '/places/$placeId'
    | '/places/new'
    | '/roasters/$roasterId'
    | '/roasters/new'
    | '/shots/$shotId'
    | '/shots/new'
    | '/visits/$visitId'
    | '/visits/new'
    | '/beans/'
    | '/gear/'
    | '/places/'
    | '/roasters/'
    | '/shots/'
    | '/visits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatsRoute: typeof StatsRoute
  BeansBeanIdRoute: typeof BeansBeanIdRoute
  BeansNewRoute: typeof BeansNewRoute
  GearGearIdRoute: typeof GearGearIdRoute
  GearNewRoute: typeof GearNewRoute
  PlacesPlaceIdRoute: typeof PlacesPlaceIdRoute
  PlacesNewRoute: typeof PlacesNewRoute
  RoastersRoasterIdRoute: typeof RoastersRoasterIdRoute
  RoastersNewRoute: typeof RoastersNewRoute
  ShotsShotIdRoute: typeof ShotsShotIdRoute
  ShotsNewRoute: typeof ShotsNewRoute
  VisitsVisitIdRoute: typeof VisitsVisitIdRoute
  VisitsNewRoute: typeof VisitsNewRoute
  BeansIndexRoute: typeof BeansIndexRoute
  GearIndexRoute: typeof GearIndexRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
  RoastersIndexRoute: typeof RoastersIndexRoute
  ShotsIndexRoute: typeof ShotsIndexRoute
  VisitsIndexRoute: typeof VisitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/': {
      id: '/visits/'
      path: '/visits'
      fullPath: '/visits/'
      preLoaderRoute: typeof VisitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shots/': {
      id: '/shots/'
      path: '/shots'
      fullPath: '/shots/'
      preLoaderRoute: typeof ShotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roasters/': {
      id: '/roasters/'
      path: '/roasters'
      fullPath: '/roasters/'
      preLoaderRoute: typeof RoastersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear/': {
      id: '/gear/'
      path: '/gear'
      fullPath: '/gear/'
      preLoaderRoute: typeof GearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/': {
      id: '/beans/'
      path: '/beans'
      fullPath: '/beans/'
      preLoaderRoute: typeof BeansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/new': {
      id: '/visits/new'
      path: '/visits/new'
      fullPath: '/visits/new'
      preLoaderRoute: typeof VisitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/$visitId': {
      id: '/visits/$visitId'
      path: '/visits/$visitId'
      fullPath: '/visits/$visitId'
      preLoaderRoute: typeof VisitsVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shots/new': {
      id: '/shots/new'
      path: '/shots/new'
      fullPath: '/shots/new'
      preLoaderRoute: typeof ShotsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shots/$shotId': {
      id: '/shots/$shotId'
      path: '/shots/$shotId'
      fullPath: '/shots/$shotId'
      preLoaderRoute: typeof ShotsShotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roasters/new': {
      id: '/roasters/new'
      path: '/roasters/new'
      fullPath: '/roasters/new'
      preLoaderRoute: typeof RoastersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roasters/$roasterId': {
      id: '/roasters/$roasterId'
      path: '/roasters/$roasterId'
      fullPath: '/roasters/$roasterId'
      preLoaderRoute: typeof RoastersRoasterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/new': {
      id: '/places/new'
      path: '/places/new'
      fullPath: '/places/new'
      preLoaderRoute: typeof PlacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$placeId': {
      id: '/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof PlacesPlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear/new': {
      id: '/gear/new'
      path: '/gear/new'
      fullPath: '/gear/new'
      preLoaderRoute: typeof GearNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear/$gearId': {
      id: '/gear/$gearId'
      path: '/gear/$gearId'
      fullPath: '/gear/$gearId'
      preLoaderRoute: typeof GearGearIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/new': {
      id: '/beans/new'
      path: '/beans/new'
      fullPath: '/beans/new'
      preLoaderRoute: typeof BeansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beans/$beanId': {
      id: '/beans/$beanId'
      path: '/beans/$beanId'
      fullPath: '/beans/$beanId'
      preLoaderRoute: typeof BeansBeanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatsRoute: StatsRoute,
  BeansBeanIdRoute: BeansBeanIdRoute,
  BeansNewRoute: BeansNewRoute,
  GearGearIdRoute: GearGearIdRoute,
  GearNewRoute: GearNewRoute,
  PlacesPlaceIdRoute: PlacesPlaceIdRoute,
  PlacesNewRoute: PlacesNewRoute,
  RoastersRoasterIdRoute: RoastersRoasterIdRoute,
  RoastersNewRoute: RoastersNewRoute,
  ShotsShotIdRoute: ShotsShotIdRoute,
  ShotsNewRoute: ShotsNewRoute,
  VisitsVisitIdRoute: VisitsVisitIdRoute,
  VisitsNewRoute: VisitsNewRoute,
  BeansIndexRoute: BeansIndexRoute,
  GearIndexRoute: GearIndexRoute,
  PlacesIndexRoute: PlacesIndexRoute,
  RoastersIndexRoute: RoastersIndexRoute,
  ShotsIndexRoute: ShotsIndexRoute,
  VisitsIndexRoute: VisitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
